version: '3.8'

services:
  app:
    image: teste
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    group_add:
      - audio
